#!/bin/sh
# WARNING: REQUIRES /bin/sh
#
# - must run on /bin/sh on solaris 9
# - must run on /bin/sh on AIX 6.x
# - if you think you are a bash wizard, you probably do not understand
#   this programming language.  do not touch.
# - if you are under 40, get peer review from your elders.
#
# Install a full Opscode Client
#

PROGNAME=`basename $0`
INSTALLER_DIR=/opt/riyic
CONFIG_DIR=/etc/riyic
USAGE="usage: $0"

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

is_smartos()
{
  uname -v | grep "^joyent" 2>&1 >/dev/null
}

if is_smartos; then
    PREFIX="/opt/local"
else
    PREFIX="/usr"
fi


if [ ! -f "$CONFIG_DIR/lambom.conf" ]; then
  mkdir -p ${CONFIG_DIR} || error_exit "Cannot create ${CONFIG_DIR}!"
  (
  cat <<'EOP'
# lambom Riyic client config file
# It's in YAML format!

# server uuid
# server: 1ca71cd6-08c4-4855-9381-2f41aeffe59c

# path to private key file
# private_key_file: /etc/riyic/private.pem

# chef loglevel
# loglevel: debug
EOP
  ) > ${CONFIG_DIR}/lambom.conf
  chmod 644 ${CONFIG_DIR}/lambom.conf
fi  

# rm -f before ln -sf is required for solaris 9
rm -f $PREFIX/bin/chef-client
rm -f $PREFIX/bin/chef-solo
rm -f $PREFIX/bin/chef-apply
rm -f $PREFIX/bin/chef-shell
rm -f $PREFIX/bin/knife
rm -f $PREFIX/bin/shef
rm -f $PREFIX/bin/ohai
rm -f $PREFIX/bin/lambom
rm -f $PREFIX/bin/berks

#ln -sf $INSTALLER_DIR/bin/chef-solo $PREFIX/bin || error_exit "Cannot link chef-solo to $PREFIX/bin"
#if [ -f "$INSTALLER_DIR/bin/chef-apply" ]; then
#  ln -sf $INSTALLER_DIR/bin/chef-apply $PREFIX/bin || error_exit "Cannot link chef-apply to $PREFIX/bin"
#fi
#if [ -f "$INSTALLER_DIR/bin/chef-shell" ]; then
#  ln -sf $INSTALLER_DIR/bin/chef-shell $PREFIX/bin || error_exit "Cannot link chef-shell to $PREFIX/bin"
#fi
#ln -sf $INSTALLER_DIR/bin/knife $PREFIX/bin || error_exit "Cannot link knife to $PREFIX/bin"
#if [ -f "$INSTALLER_DIR/bin/shef" ]; then
#  ln -sf $INSTALLER_DIR/bin/shef $PREFIX/bin || error_exit "Cannot link shef to $PREFIX/bin"
#fi
#ln -sf $INSTALLER_DIR/bin/ohai $PREFIX/bin || error_exit "Cannot link ohai to $PREFIX/bin"
#
## We test for the presence of /usr/bin/chef-client to know if this script succeeds, so this
## must appear as the last real action in the script
#ln -sf $INSTALLER_DIR/bin/chef-client $PREFIX/bin || error_exit "Cannot link chef-client to $PREFIX/bin"
#
#ln -sf $INSTALLER_DIR/bin/lambom $PREFIX/bin || error_exit "Cannot link lambom to $PREFIX/bin"
#ln -sf $INSTALLER_DIR/bin/berks $PREFIX/bin || error_exit "Cannot link berks to $PREFIX/bin"

#
# install wrapper script to bypass CHEF-3581 bug with ruby env vars
#
(
cat <<'EOP'
#!/bin/sh
unset GEM_HOME
unset GEM_PATH
unset RUBYOPT
/opt/riyic/bin/${0##*/} $*
EOP
) > $PREFIX/bin/riyic-wrapper
chmod 750 $PREFIX/bin/riyic-wrapper

ln -sf $INSTALLER_DIR/bin/chef-solo $PREFIX/bin/riyic-wrapper || error_exit "Cannot link chef-solo to $PREFIX/bin"
ln -sf $INSTALLER_DIR/bin/chef-apply $PREFIX/bin/riyic-wrapper || error_exit "Cannot link chef-apply to $PREFIX/bin"
ln -sf $INSTALLER_DIR/bin/chef-shell $PREFIX/bin/riyic-wrapper || error_exit "Cannot link chef-shell to $PREFIX/bin"
ln -sf $INSTALLER_DIR/bin/shef $PREFIX/bin/riyic-wrapper || error_exit "Cannot link shef to $PREFIX/bin"
ln -sf $INSTALLER_DIR/bin/ohai $PREFIX/bin/riyic-wrapper || error_exit "Cannot link ohai to $PREFIX/bin"
ln -sf $INSTALLER_DIR/bin/chef-client $PREFIX/bin/riyic-wrapper || error_exit "Cannot link chef-client to $PREFIX/bin"
ln -sf $INSTALLER_DIR/bin/lambom $PREFIX/bin/riyic-wrapper || error_exit "Cannot link lambom to $PREFIX/bin"
ln -sf $INSTALLER_DIR/bin/berks $PREFIX/bin/riyic-wrapper || error_exit "Cannot link berks to $PREFIX/bin"

# si non esta instalado curl en el sistema, usamos o noso
if [ ! -f "$PREFIX/bin/curl" ]; then
  ln -sf $INSTALLER_DIR/embedded/bin/curl $PREFIX/bin || error_exit "Cannot link curl to $PREFIX/bin"
fi

echo "Installation complete"

exit 0
